# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8ea474b0b4e33a2b6f61da1752dcfdfabf52fdd7565244cbb03061e6367f25fa113188f2c598624324af8b250eb0fb566ed2629eac52e47f0713f2ce891ae6d

test:
  secret_key_base: 5f4a777a69f623de094df207bd91868409af7f260fad4c6e6d53b04ee04c43bc2a65cc1629d053ad3eb3c89d903d215d1fce7bc732c5de8917f28f05efeabdd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
